# Generated by Django 3.0.8 on 2020-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptografias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chave_cesar_apenas_letras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='chave_cesar_varios_caracteres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='chave_vigenere_apenas_letras',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='chave_vigenere_varios_caracteres',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_comum_subst_simples_apenas_letras',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_comum_subst_simples_varios_caracteres',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_encript_subst_simples_apenas_letras',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_encript_subst_simples_varios_caracteres',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
