# Generated by Django 3.0.8 on 2020-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptografias', '0002_auto_20201124_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chave_vigenere_apenas_letras',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='chave_vigenere_varios_caracteres',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_comum_subst_simples_apenas_letras',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_comum_subst_simples_varios_caracteres',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_encript_subst_simples_apenas_letras',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='msg_encript_subst_simples_varios_caracteres',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
